[HSEARCH] Allow to use docker for the hsearch-elasticsearch-wikipedia demo

diff --git a/hibernate-search/hsearch-elasticsearch-wikipedia/src/init/init b/hibernate-search/hsearch-elasticsearch-wikipedia/src/init/init
--- a/hibernate-search/hsearch-elasticsearch-wikipedia/src/init/init
+++ b/hibernate-search/hsearch-elasticsearch-wikipedia/src/init/init
@@ -19,9 +19,57 @@ function guess_remote_dump_url() {
 		|| abort "Could not guess the URL to get the remote dump from."
 }
 
-LOCAL_DUMP_FILE=$1
+function do_psql() {
+	if [ -n "$DOCKER_CONTAINER_NAME" ]
+	then
+		sudo -p "Sudo password (to execute docker): " docker run -i --rm --link "$DOCKER_CONTAINER_NAME":postgres -e PGPASSWORD=hibernate_demo postgres:11.1 psql -h postgres -U hibernate_demo hsearch_es_wikipedia
+	else
+		PGPASSWORD=hibernate_demo psql -U hibernate_demo -h localhost -W hsearch_es_wikipedia
+	fi
+}
+
 
 which xsltproc 1>/dev/null 2>&1 || abort "Command 'xsltproc' isn't in the \$PATH; please install the command or add it to the \$PATH."
+
+while getopts 'd:' opt
+do
+        case "$opt" in
+                d)
+			DOCKER_CONTAINER_NAME="$OPTARG"
+			log "Will attempt to connect to docker container with name '$DOCKER_CONTAINER_NAME'"
+                        ;;
+                h)
+                        FEATURE=git_history
+                        ;;
+                f)
+                        case "$OPTARG" in
+                                "api"|"spi"|"public"|"impl"|"test"|"main"|"all")
+                                        FILTER="$OPTARG"
+                                        ;;
+                                *)
+                                        echo 2>&1 "Unrecognized source filter: $OPTARG"
+                                        exit 1
+                                        ;;
+                        esac
+                        ;;
+                i)
+                        INTERNAL_PACKAGE_MARKER="$OPTARG"
+                        ;;
+                \?)
+                        exit 1
+                        ;;
+        esac
+done
+
+shift $(( OPTIND - 1 ))
+
+if [ -z "$DOCKER_CONTAINER_NAME" ]
+then
+	log "No docker container name given (-d option missing). Will attempt to use a local 'psql' command."
+	which "psql" 1>/dev/null 2>&1 || abort "Command 'psql' isn't in the \$PATH; please install the command or add it to the \$PATH."
+fi
+
+LOCAL_DUMP_FILE=$1
 
 if [ -z "$LOCAL_DUMP_FILE" ]
 then
@@ -48,5 +96,5 @@ fi
 
 DIR=$(readlink -f "$0" | xargs dirname)
 
-xsltproc "$DIR/sql_populate.xslt" $LOCAL_DUMP_FILE | psql -U hibernate_demo -h localhost -W hsearch_es_wikipedia
+xsltproc "$DIR/sql_populate.xslt" $LOCAL_DUMP_FILE | do_psql
 
